version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: python main.py
      # Add build step here
      - run: |
          echo "Building Docker image"
          docker build -t "$DOCKER_USERNAME/circleci-test:latest" .
      # Add push step heree
      - run: |
          echo "Pushing Docker image to Docker Hub"
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USERNAME/circleci-test:latest
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
